/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package depAnalysisTest;
//import org.postgresql.util.URLCoder;;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

//private URLCoder getB64() {
        //return new URLCoder();
    //}
}
